global:
  image:
    tag: "v2.9.3"

server:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    ports:
      - name: http
        port: 8080
        targetPort: 8080
        protocol: TCP
      - name: https
        port: 443
        targetPort: 8080
        protocol: TCP
  extraArgs:
    - --insecure
    - --port=8080

redis:
  enabled: true

dex:
  enabled: false

controller:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi