apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
  namespace: docker-demo-namespace
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: app-server
  template:
    metadata:
      name: app-server
      labels: 
        app: app-server
    spec:
      imagePullSecrets:
        - name: docker-hub-creds
      containers:
        - name: app-server
          image: makanist/docker-kubernetes-test:latest  # or use specific version like :1.0.0
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: app-server-service
  namespace: docker-demo-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels: 
    app: app-server
spec:
  type: LoadBalancer
  selector:
    app: app-server
  ports:
    - port: 3000