grafana:
  enabled: true
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    port: 80
    targetPort: 3000
  # Add Loki datasource automatically
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      jsonData:
        maxLines: 1000

loki:
  enabled: true
  persistence:
    enabled: false
  service:
    port: 3100

prometheus:
  enabled: true
  nodeExporter:
    enabled: false  # Disable node-exporter on Mac
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false
    service:
      type: ClusterIP
    extraScrapeConfigs: |
      - job_name: 'nodejs-app'
        scrape_interval: 10s
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints  # Changed from service to endpoints
            namespaces:
              names:
                - docker-demo-namespace
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: app-server-service
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "3000"
            action: keep
          - target_label: app
            replacement: contacts-service
          - target_label: environment
            replacement: development