apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker.io/makanist/docker-kubernetes-test
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/app.pull-secret: pull-secret:argocd/dockerhub-secret
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/app.kustomize.image-name: makanist/docker-kubernetes-test
spec:
  project: nodejs-project
  source:
    repoURL: https://github.com/makanist-org/docker_k8s_demo.git
    targetRevision: HEAD
    path: k8s/manifests
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-demo-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true