apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: nodejs-project
  source:
    repoURL: git@github.com:makanist-org/docker_k8s_demo.git
    targetRevision: HEAD
    path: k8s/manifests # Path to the Kubernetes manifests for application
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-demo-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true