apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nodejs=makanist/docker-kubernetes-test
    argocd-image-updater.argoproj.io/nodejs.update-strategy: semver
    argocd-image-updater.argoproj.io/nodejs.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/nodejs.pull-secret: pull-secret:argocd/dockerhub-secret
spec:
  project: nodejs-project
  source:
    repoURL: git@github.com:makanist-org/docker_k8s_demo.git
    targetRevision: HEAD
    path: k8s/manifests # Path to the Kubernetes manifests for application
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-demo-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true