apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: argocd
  labels:
    argocd-image-updater.argoproj.io/secret-type: pull-secret
type: kubernetes.io/dockerconfigjson
data:
  # This is a placeholder. Replace with your actual Docker credentials
  # To generate this value, run:
  # kubectl create secret docker-registry dockerhub-secret --docker-server=https://index.docker.io/v1/ --docker-username=<username> --docker-password=<password> --docker-email=<email> -o yaml --dry-run=client
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ5b3VyLXVzZXJuYW1lIiwicGFzc3dvcmQiOiJ5b3VyLXBhc3N3b3JkIiwiZW1haWwiOiJ5b3VyLWVtYWlsQGV4YW1wbGUuY29tIiwiYXV0aCI6ImVtOTFjaTExYzJWeWJtRnRaVHB1YjNSaGNtVmhiREZ3WVhOemQyOXlaQT09In19fQ==