apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nodejs-project
  namespace: argocd
spec:
  description: Project for NodeJS applications
  sourceRepos:
  - https://github.com/makanist-org/docker_k8s_demo.git
  destinations:
  - namespace: docker-demo-namespace
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'