apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:makanist/Docker_k8s_demo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD39cP5sthXRxH43pgF3ds/gB+ygFOkS/+S1sZIsd0z8wAAAJiONR/tjjUf
    7QAAAAtzc2gtZWQyNTUxOQAAACD39cP5sthXRxH43pgF3ds/gB+ygFOkS/+S1sZIsd0z8w
    AAAEA6VDde9ZCOCZwRP0z7eWbZzSyvjnx9M+SIhaV4/TqEiff1w/my2FdHEfjemAXd2z+A
    H7KAU6RL/5LWxkix3TPzAAAAEGFyZ29jZEBrOHMubG9jYWwBAgMEBQ==
    -----END OPENSSH PRIVATE KEY-----